export const environment = {
  production: false,
  buildMode: 'local',
  baseURL: 'https://iempapi-dev.myx0platform.com/usecase',
  transformBaseURL: 'https://iempapi-dev.myx0platform.com/transform',
  showcaseBaseURL: 'https://iempapi-dev.myx0platform.com',
  showcaseURL: 'https://iemp-dev.myx0platform.com',
  transformURL: 'https://iemp-dev.myx0platform.com/transform',
  APIVersion: '1',
  tenant: 'f3211d0e-125b-42c3-86db-322b19a65a22',
  clientId: '84dc9481-e8af-4943-958d-941383498b3c',
  redirectUri: 'https://localhost:44314',
  postLogoutRedirectUri: 'https://localhost:44314',
  consentScope: 'ad4afda0-0925-4d98-8cf3-795d2eb49062/user_impersonation',
  apiUrl: 'https://iempapi-dev.myx0platform.com/usecase',
  myIndustryURL: 'https://in.accenture.com/industryx/new-upcoming/',
  emailMode: ' - [DEV environment]',
  toEmail: 'IndustryX_Testing@accenture.com',
  solutionURL: 'https://iemp-dev.myx0platform.com/asset/',
  toolURL: 'https://iemp-dev.myx0platform.com/tool/',
  challengeUrl: 'https://iemp-dev.myx0platform.com/challenge/',
  isFromKGCheck: true,
  faqUrl:
    'https://kxdocuments.accenture.com/contribution/052946dc-9036-4174-b98f-c14d706152c4',
  uafURL: '',
  showcaseCLientURL: 'https://iemp-dev.myx0platform.com',
  isShowcaseEnabled: true,
};
