export const environment = {
  production: false,
  buildMode: 'subdev',
  baseURL: 'https://iempapi-dev1.myx0platform.com/usecase',
  transformBaseURL: 'https://iempapi-dev1.myx0platform.com/transform',
  showcaseBaseURL: 'https://iempapi-dev1.myx0platform.com',
  showcaseURL: 'https://iemp-dev1.myx0platform.com',
  transformURL: 'https://iemp-dev1.myx0platform.com/transform',
  APIVersion: '1',
  tenant: 'f3211d0e-125b-42c3-86db-322b19a65a22',
  clientId: 'b2ac2c9f-622f-4755-8b93-16ef36acf80e',
  redirectUri: 'https://iemp-dev1.myx0platform.com/usecase',
  postLogoutRedirectUri: 'https://iemp-dev1.myx0platform.com/usecase',
  consentScope: '7e980a9e-2d1e-4f5d-9389-404b7d4d1100/user_impersonation',
  apiUrl: 'https://iempapi-dev1.myx0platform.com/usecase',
  myIndustryURL: 'https://in.accenture.com/industryx/new-upcoming/',
  emailMode: ' - [DEV1 environment]',
  toEmail: 'IndustryX_Testing@accenture.com',
  solutionURL: 'https://iemp-dev1.myx0platform.com/asset/',
  toolURL: 'https://iemp-dev1.myx0platform.com/tool/',
  challengeUrl: 'https://iemp-dev1.myx0platform.com/challenge/',
  isFromKGCheck: true,
  faqUrl:
    'https://kxdocuments.accenture.com/contribution/052946dc-9036-4174-b98f-c14d706152c4',
  uafURL: 'https://mydiagnostic-uaf-dev1.aiam-dh.com',
  showcaseCLientURL: 'https://iemp-dev1.myx0platform.com',
  isShowcaseEnabled: true,
};
