export const environment = {
  production: true,
  baseURL: 'https://iempapi.accenture.com/usecase',
  transformBaseURL: 'https://iempapi.accenture.com/transform',
  showcaseBaseURL: 'https://iempapi.accenture.com',
  transformURL: 'https://iemp.accenture.com/transform',
  showcaseURL: 'https://iemp.accenture.com/',
  APIVersion: '1',
  buildMode: 'subprod',
  emailMode: '',
  toEmail: 'IEMP_ProdSupport@accenture.com',
  tenant: 'e0793d39-0939-496d-b129-198edd916feb',
  clientId: '5d3e69c8-867b-4de2-bd61-827a6ba81a70',
  redirectUri: 'https://iemp.accenture.com/usecase',
  postLogoutRedirectUri: 'https://iemp.accenture.com/usecase',
  consentScope: 'acddca97-ef33-4c77-899b-93e8680c4aea/user_impersonation',
  apiUrl: 'https://iempapi.accenture.com/usecase',
  myIndustryURL: 'https://in.accenture.com/industryx/new-upcoming/',
  solutionURL: 'https://iemp.accenture.com/asset/',
  toolURL: 'https://iemp.accenture.com/tool/',
  challengeUrl: 'https://iemp.accenture.com/challenge/',
  isFromKGCheck: false,
  faqUrl:
    'https://kxdocuments.accenture.com/contribution/052946dc-9036-4174-b98f-c14d706152c4',
  uafURL: 'https://mydiagnostic-portal.accenture.com/en/Gallery?app=IEMP',
  showcaseCLientURL: 'https://iemp.accenture.com',
  isShowcaseEnabled: true,
};
