export const environment = {
  production: true,
  buildMode: 'subpreprod',
  emailMode: '',
  toEmail: 'IEMP_ProdSupport@accenture.com',
  baseURL: 'https://iempapi-preprod.accenture.com/usecase',
  transformBaseURL: 'https://iempapi-preprod.accenture.com/transform',
  showcaseBaseURL: 'https://iempapi-preprod.accenture.com',
  transformURL: 'https://iemp-preprod.accenture.com/transform',
  showcaseURL: 'https://iemp-preprod.accenture.com/',
  APIVersion: '1',
  tenant: 'e0793d39-0939-496d-b129-198edd916feb',
  clientId: '7f1f0798-727d-47d5-a41e-c76d5a505bee',
  redirectUri: 'https://iemp-preprod.accenture.com/usecase',
  postLogoutRedirectUri: 'https://iemp-preprod.accenture.com/usecase',
  consentScope: '3b280d4c-984b-4357-b16b-c469a672c977/user_impersonation',
  apiUrl: 'https://iempapi-preprod.accenture.com/usecase',
  myIndustryURL: 'https://in.accenture.com/industryx/new-upcoming/',
  solutionURL: 'https://iemp-preprod.accenture.com/asset/',
  toolURL: 'https://iemp-preprod.accenture.com/tool/',
  challengeUrl: 'https://iemp-preprod.accenture.com/challenge/',
  isFromKGCheck: false,
  faqUrl:
    'https://kxdocuments.accenture.com/contribution/052946dc-9036-4174-b98f-c14d706152c4',
  uafURL: '',
  showcaseCLientURL: 'https://iemp-preprod.accenture.com',
  isShowcaseEnabled: true,
};
