export const environment = {
  production: true,
  buildMode: 'subdemo',
  baseURL: 'https://iempapi-demo.accenture.com/usecase',
  transformBaseURL: 'https://iempapi-demo.accenture.com/transform',
  showcaseBaseURL: 'https://iempapi-demo.accenture.com',
  transformURL: 'https://iemp-demo.accenture.com/transform',
  showcaseURL: 'https://iemp-demo.accenture.com/',
  APIVersion: '1',
  tenant: 'e0793d39-0939-496d-b129-198edd916feb',
  clientId: 'd6d4816d-6494-4cc9-9fbd-50968d4d50ea',
  redirectUri: 'https://iemp-demo.accenture.com/usecase',
  postLogoutRedirectUri: 'https://iemp-demo.accenture.com/usecase',
  consentScope: 'c3a6f999-091a-4303-a085-47b56fe1b56d/user_impersonation',
  apiUrl: 'https://iempapi-demo.accenture.com/usecase',
  myIndustryURL: 'https://in.accenture.com/industryx/new-upcoming/',
  emailMode: '-[TRAINING environment]',
  toEmail: 'IEMP_BA-Test@accenture.com',
  solutionURL: 'https://iemp-demo.accenture.com/asset/',
  toolURL: 'https://iemp-demo.accenture.com/tool/',
  challengeUrl: 'https://iemp-demo.accenture.com/challenge/',
  isFromKGCheck: false,
  faqUrl:
    'https://kxdocuments.accenture.com/contribution/052946dc-9036-4174-b98f-c14d706152c4',
  uafURL: 'https://mydiagnostic-portal.accenture.com/en/Gallery?app=IEMP',
  showcaseCLientURL: 'https://iemp-demo.accenture.com',
  isShowcaseEnabled: true,
};
