export const environment = {
  production: true,
  buildMode: 'substage',
  baseURL: 'https://iempapi-stage.accenture.com/usecase',
  transformBaseURL: 'https://iempapi-stage.accenture.com/transform',
  showcaseBaseURL: 'https://iempapi-stage.accenture.com',
  transformURL: 'https://iemp-stage.accenture.com/transform',
  showcaseURL: 'https://iemp-stage.accenture.com/',
  APIVersion: '1',
  tenant: 'e0793d39-0939-496d-b129-198edd916feb',
  clientId: '942591a6-0074-4476-951a-b40f6592c202',
  redirectUri: 'https://iemp-stage.accenture.com/usecase',
  postLogoutRedirectUri: 'https://iemp-stage.accenture.com/usecase',
  consentScope: '1117299e-8168-47d6-b427-7b8087f77b43/user_impersonation',
  apiUrl: 'https://iempapi-stage.accenture.com/usecase',
  myIndustryURL: 'https://in.accenture.com/industryx/new-upcoming/',
  emailMode: '-[STAGE environment]',
  toEmail: 'IndustryX_Testing@accenture.com',
  solutionURL: 'https://iemp-stage.accenture.com/asset/',
  toolURL: 'https://iemp-stage.accenture.com/tool/',
  challengeUrl: 'https://iemp-stage.accenture.com/challenge/',
  isFromKGCheck: false,
  faqUrl:
    'https://kxdocuments.accenture.com/contribution/052946dc-9036-4174-b98f-c14d706152c4',
  uafURL: '',
  showcaseCLientURL: 'https://iemp-stage.accenture.com',
  isShowcaseEnabled: true,
};
