export const environment = {
  production: true,
  buildMode: 'subapt',
  baseURL: 'https://iempapi-apt.myx0platform.com/usecase',
  transformBaseURL: 'https://iempapi-apt.myx0platform.com/transform',
  showcaseBaseURL: 'https://iempapi-apt.myx0platform.com',
  transformURL: 'https://iemp-apt.myx0platform.com/transform',
  showcaseURL: 'https://iemp-apt.myx0platform.com',
  APIVersion: '1',
  tenant: 'e0793d39-0939-496d-b129-198edd916feb',
  clientId: '6044044b-3e5c-48b4-bc2d-b6f3e4f7c16c',
  redirectUri: 'https://iemp-apt.myx0platform.com/usecase',
  postLogoutRedirectUri: 'https://iemp-apt.myx0platform.com/usecase',
  consentScope: '6e53af06-e89d-46dc-aff0-512cfa36574d/user_impersonation',
  apiUrl: 'https://iempapi-apt.myx0platform.com/usecase',
  myIndustryURL: 'https://in.accenture.com/industryx/new-upcoming/',
  emailMode: '-[APT environment]',
  toEmail: 'IndustryX_Testing@accenture.com',
  solutionURL: 'https://iemp-apt.myx0platform.com/asset/',
  toolURL: 'https://iemp-apt.myx0platform.com/tool/',
  challengeUrl: 'https://iemp-apt.myx0platform.com/challenge/',
  isFromKGCheck: false,
  faqUrl:
    'https://kxdocuments.accenture.com/contribution/052946dc-9036-4174-b98f-c14d706152c4',
  uafURL: '',
  showcaseCLientURL: 'https://iemp-apt.myx0platform.com',
  isShowcaseEnabled: true,
};
