export const environment = {
  production: true,
  buildMode: 'subtest',
  baseURL: 'https://iempapi-test1.myx0platform.com/usecase',
  transformBaseURL: 'https://iempapi-test1.myx0platform.com/transform',
  showcaseBaseURL: 'https://iempapi-test1.myx0platform.com',
  showcaseURL: 'https://iemp-test1.myx0platform.com',
  transformURL: 'https://iemp-test1.myx0platform.com/transform',
  APIVersion: '1',
  tenant: 'e0793d39-0939-496d-b129-198edd916feb',
  clientId: 'fe209f6c-adde-4461-b55c-8cbe30850313',
  redirectUri: 'https://iemp-test1.myx0platform.com/usecase',
  postLogoutRedirectUri: 'https://iemp-test1.myx0platform.com/usecase',
  consentScope: '7c8ecebc-8fdc-4ef5-8e8a-8114b9f4ea97/user_impersonation',
  apiUrl: 'https://iempapi-test1.myx0platform.com/usecase',
  myIndustryURL: 'https://in.accenture.com/industryx/new-upcoming/',
  emailMode: ' - [PT environment]',
  toEmail: 'IEMP_BA-Test@accenture.com',
  solutionURL: 'https://iemp-test1.myx0platform.com/asset/',
  toolURL: 'https://iemp-test1.myx0platform.com/tool/',
  challengeUrl: 'https://iemp-test1.myx0platform.com/challenge/',
  isFromKGCheck: false,
  faqUrl:
    'https://kxdocuments.accenture.com/contribution/052946dc-9036-4174-b98f-c14d706152c4',
  uafURL: 'https://mydiagnostics2.stage.accenture.com/Gallery?app=IEMP',
  showcaseCLientURL: 'https://iemp-test1.myx0platform.com',
  isShowcaseEnabled: true,
};
