export const environment = {
  production: true,
  buildMode: 'subtest',
  baseURL: 'https://iempapi-test.myx0platform.com/usecase',
  transformBaseURL: 'https://iempapi-test.myx0platform.com/transform',
  showcaseBaseURL: 'https://iempapi-test.myx0platform.com',
  showcaseURL: 'https://iemp-test.myx0platform.com',
  transformURL: 'https://iemp-test.myx0platform.com/transform',
  APIVersion: '1',
  tenant: 'e0793d39-0939-496d-b129-198edd916feb',
  clientId: '9fd81b53-ca07-4a5c-b47f-89784fd4c166',
  redirectUri: 'https://iemp-test.myx0platform.com/usecase',
  postLogoutRedirectUri: 'https://iemp-test.myx0platform.com/usecase',
  consentScope: '0545151a-7b66-44d2-804a-2843b8262232/user_impersonation',
  apiUrl: 'https://iempapi-test.myx0platform.com/usecase',
  myIndustryURL: 'https://in.accenture.com/industryx/new-upcoming/',
  emailMode: ' - [PT environment]',
  toEmail: 'IEMP_BA-Test@accenture.com',
  solutionURL: 'https://iemp-test.myx0platform.com/asset/',
  toolURL: 'https://iemp-test.myx0platform.com/tool/',
  challengeUrl: 'https://iemp-test.myx0platform.com/challenge/',
  isFromKGCheck: false,
  faqUrl:
    'https://kxdocuments.accenture.com/contribution/052946dc-9036-4174-b98f-c14d706152c4',
  uafURL: 'https://mydiagnostics2.stage.accenture.com/Gallery?app=IEMP',
  showcaseCLientURL: 'https://iemp-test.myx0platform.com',
  isShowcaseEnabled: true,
};
